name: LDCheck

on:
  workflow_dispatch:
    inputs:
      DEVICE_TREE_URL:
        description: 'DEVICE_TREE_URL'
        required: true
        default: 'https://github.com/hdzungx/android_device_xiaomi_picasso_twrp.git'
      DEVICE_TREE_BRANCH:
        description: 'DEVICE_TREE_BRANCH'
        required: true
        default: 'android-12.1'
      DEVICE_PATH:
        description: 'DEVICE_PATH'
        required: true
        default: 'device/xiaomi/picasso'
      DEVICE_NAME:
        description: 'DEVICE_NAME'
        required: true
        default: 'picasso'
jobs:
  make:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
        architecture: x64
        
    - name: Init environment
      run: |
        cd ~
        python -m pip install wheel
        python -m pip install protobuf==3.19.4
        python -m pip install bsdiff4
        python -m pip install requests
        sudo apt-get install -y axel
    - name: LD Check
      run: |
        PATH=~/bin:$PATH
        cd ${{ steps.pwd.outputs.pwd }}
        git clone ${{ github.event.inputs.DEVICE_TREE_URL }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./${{ github.event.inputs.DEVICE_PATH }}
        cd './device/xiaomi/picasso'
        cd './recovery/root'
        axel -n 4 https://github.com/that1/ldcheck/archive/refs/heads/master.zip -o ldcheck.zip
        unzip -ldcheck.zip -d /recovery/root && rm -v ldcheck.zip
        python ldcheck -p system/lib64:vendor/lib64 -d system/bin/qseecomd
